print('brbr patapim')
print('brbr patapim')
print('brbr patapim')
print('brbr patapim')
print('brbr patapim')
print('brbr patapim')
print('brbr patapim')
print('brbr patapim')

print('brbr patapim')
print('brbr patapim')
print('brbr patapim')
